name: Deploy to Production on Tag Creation for Main Branch
"on":
  push:
    tags:
      - "v*" # Matches any tag pushed starting with v
    branches:
      - main # Ensures the tag is associated with the main branch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_FIREBASE_TOKEN: "${{ secrets.FIREBASE_LOGIN_TOKEN }}"
      REACT_APP_PROJECT_ICON_TOKEN: "${{secrets.FIREBASE_PROJECT_ICON_TOKEN}}"
      REACT_APP_RESUME_TOKEN: "${{secrets.FIREBASE_RESUME_TOKEN}}"
      REACT_APP_TAG_NAME: "${{ github.ref_name }}"
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "REACT_APP_TAG_NAME=$REACT_APP_TAG_NAME"
          echo "GitHub ref_name=${{ github.ref_name }}"
      - run: npm --version
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASHWIJA_NAYAK }}"
          target: "prod-instance"
          projectId: "${{ secrets.PROD_PROJECT_ID }}"
          channelId: live
